version: "3"
   
services:
    django_model_service:
        build:
            context: ./modelService
            dockerfile: dockerfile
        container_name: django_model
        command: python manage.py runserver 0.0.0.0:9004
        volumes:
            - .:/usr/src/app/
        ports:
            - "9004:9004"
        environment:
            - DEBUG=1
            - CELERY_BROKER=guest@rabbitmq:5672
        depends_on:
            - rabbitmq
            - mongodb
        networks:
            - appnet

    worker:
        build:
            context: ./modelService
        command: celery -A modelService worker --pool threads -l info
        depends_on:
           - rabbitmq
        networks:
          - appnet

    rabbitmq:
      image: rabbitmq:3.8
      networks:
          - appnet   


    django_query_service:
        build:
            context: ./queryResultsService
            dockerfile: dockerfile
        container_name: django_query
        command: python manage.py runserver 0.0.0.0:9005
        volumes:
            - .:/usr/src/app/
        ports:
            - "9005:9005"
        environment:
            - DEBUG=1
        depends_on:
            - mongodb
        networks:
            - appnet      
        

    # worker_2:
    #     build: .
    #     command: celery -A modelService worker --pool threads -l info
    #     depends_on:
    #        - rabbitmq
    #     networks:
    #       - appnet  
    #     mem_limit: 2g      

    # worker_3:
    #     build: .
    #     command: celery -A modelService worker --pool threads -l info
    #     depends_on:
    #        - rabbitmq
    #     networks:
    #       - appnet        
    #     mem_limit: 2g

    # worker_4:
    #     build: .
    #     command: celery -A modelService worker --pool threads -l info
    #     depends_on:
    #        - rabbitmq
    #     networks:
    #       - appnet  
    #     mem_limit: 2g

    # worker_5:
    #     build: .
    #     command: celery -A modelService worker --pool threads -l info
    #     depends_on:
    #        - rabbitmq
    #     networks:
    #       - appnet
    #     mem_limit: 2g                    


       


    mongodb:
      image: mongo:latest
      restart: always
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
      networks:
          - appnet      

      volumes:
          - ./mongo-data:/data/db   


networks:
  appnet:
    driver: bridge                


